---
controller_workflows:
  - name: SETUP / Insights
    description: this workflow configures insights for this workshop
    extra_vars: ''
    inventory: Workshop Inventory
    state: present
    organization: Default
    simplified_workflow_nodes:
      - identifier: Insights / Replace Satellite Manifest
        all_parents_must_converge: false
        unified_job_template: Insights / Replace Satellite Manifest
        success_nodes: Insights / Replace Satellite Manifest
        organization: Default
      - identifier: Insights / Replace Satellite Manifest
        all_parents_must_converge: false
        unified_job_template: Insights / Install and Register
        success_nodes: Insights / Create Insights Credential
        organization: Default        
      - identifier: Insights / Create Insights Credential
        all_parents_must_converge: false
        unified_job_template: Insights / Create Insights Credential
        success_nodes: Insights / Create Insights Project
        organization: Default        
      - identifier: Insights / Create Insights Project
        all_parents_must_converge: false
        unified_job_template: Insights / Create Insights Project
        organization: Default




