---
- name: install and register insights 
  hosts: "{{ HOSTS is defined | ternary(HOSTS, PREFIX|default('')+'*') }}"
  become: yes
  gather_facts: no
  strategy: free

  tasks:
    - name: install and register insights
      include_role:
        name: redhat.insights.insights_client


#- name: install compliance packages
#  hosts: "{{ HOSTS is defined | ternary(HOSTS, PREFIX|default('')+'*') }}"
#  become: yes
#  gather_facts: no
# set to 1 to control connections to satellite for workshop satellite
#  serial: 1 

#  tasks:
    - name: install insights compliance
      include_role:
        name: redhat.insights.compliance
        tasks_from: install

