---
- name: get insight account owners manifest
  hosts: localhost

  tasks:
    - name: get manifest from bucket
      amazon.aws.aws_s3:
        bucket: "{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }}.private"
        object: manifest_insights.zip
        dest: "{{ playbook_dir }}/manifest_insights.zip"
        region: "{{ ec2_region }}"
        mode: get
      register: manifest

- name: refresh manifest
  hosts: "{{ HOSTS | default('satellite.example.com') }}"
  connection: local
  gather_facts: no
  vars:
#    refresh_satellite_manifest: no
    refresh_timeout: 14400
    refresh_retry_interval: 15

  tasks:
    - name: refresh manifest
      redhat.satellite.subscription_manifest:
        organization: "Default Organization"
        state: present
        manifest_path: "{{ playbook_dir }}/{{ ec2_name_prefix|lower }}/manifest_insights.zip"
      async: "{{ refresh_timeout }}"
      poll: 0
      register: refresh_async
#      when: refresh_satellite_manifest


- hosts: "{{ HOSTS | default('satellite.example.com') }}"
  become: true
  vars:
#    refresh_satellite_manifest: no
    refresh_timeout: 14400
    refresh_retry_interval: 15

  tasks:
    - name: >
        Watch the Satellite production.log until ManifestRefresh result ==> success appears before continuing...
      wait_for:
        path: /var/log/foreman/production.log
        search_regex: "^.*ManifestRefresh.*state\ changed.*\ stopped\ \ result.*\ success"
        timeout: 1500
        sleep: 20
#      when: refresh_satellite_manifest


        
      
