---
- hosts: "{{ HOSTS is defined | ternary(HOSTS, PREFIX|default('')+'*') }}"
  become: yes
  vars:
    env: Dev
    activation_key: undef
    sat_url: satellite.example.com
    insights: false
  roles:
    - rhsm_register

  tasks:
    - include_role:
        name: redhat.insights.insights_client
      when: insights

